/* ===== 汎用問題データ =====
   subject: 科目ID
   c: 単元番号
   s: 小分類
   n: 問題番号（科目内で一意推奨）
   d: 難易度 A/B/C
   type: "tf" | "choice" | "input"
   a:
     tf     -> true / false
     choice -> 正解番号の配列（1始まり）
     input  -> answers:[...] または number + tolerance
*/

const SUBJECTS = {
  physics: {
    name: "物理",
    chapters: {
      1: "力学", 2: "熱力学", 3: "波動", 4: "電磁気", 5: "原子"
    }
  },
  earth: {
    name: "地学",
    chapters: {
      1: "地球", 2: "地質・地史", 3: "大気・海洋", 4: "宇宙"
    }
  },
  classics: {
    name: "古典",
    chapters: {
      1: "古文単語", 2: "文法", 3: "敬語", 4: "古文読解", 5: "漢文"
    }
  },
  german: {
    name: "ドイツ語",
    chapters: {
      1: "基本動詞200"
    }
  }
};

const Q_ALL = [
  /* ---------- 物理 ---------- */
  {id:"phy-1",subject:"physics",c:1,s:"運動方程式",n:1,d:"A",type:"tf",
   q:"物体に働く合力が0なら、その物体の加速度は0である。",a:true,
   e:"運動方程式 F=ma より、合力Fが0なら加速度aも0。静止または等速直線運動になる。"},
  {id:"phy-2",subject:"physics",c:1,s:"運動方程式",n:2,d:"A",type:"choice",
   q:"質量2.0 kgの物体に6.0 Nの合力が働く。加速度はいくらか。",o:["1.0 m/s²","2.0 m/s²","3.0 m/s²","12 m/s²"],a:[3],
   e:"a=F/m=6.0/2.0=3.0 m/s²。"},
  {id:"phy-3",subject:"physics",c:1,s:"速度・加速度",n:3,d:"A",type:"choice",
   q:"位置xを時間tで1回微分した量として正しいものを選びなさい。",o:["速度","加速度","力","運動量"],a:[1],
   e:"v=dx/dt。位置の時間変化率が速度。"},
  {id:"phy-4",subject:"physics",c:1,s:"速度・加速度",n:4,d:"B",type:"input",
   q:"速度vを時間tで微分した量を、漢字2文字で答えなさい。",answers:["加速度"],aText:"加速度",
   e:"a=dv/dt なので、速度の時間変化率は加速度。"},
  {id:"phy-5",subject:"physics",c:1,s:"仕事とエネルギー",n:5,d:"B",type:"tf",
   q:"保存力だけが仕事をする場合、力学的エネルギーは保存される。",a:true,
   e:"非保存力による散逸がなければ、運動エネルギーと位置エネルギーの和は一定。"},
  {id:"phy-6",subject:"physics",c:1,s:"円運動",n:6,d:"B",type:"choice",
   q:"等速円運動をする物体の加速度の向きはどれか。",o:["接線方向","円の中心方向","円の外向き","速度と同じ向き"],a:[2],
   e:"速度の大きさは一定でも向きが変化するため、加速度は常に円の中心方向。"},
  {id:"phy-7",subject:"physics",c:2,s:"気体",n:7,d:"A",type:"tf",
   q:"理想気体の状態方程式は pV=nRT である。",a:true,
   e:"圧力p、体積V、物質量n、気体定数R、絶対温度Tの関係。"},
  {id:"phy-8",subject:"physics",c:2,s:"熱力学第一法則",n:8,d:"B",type:"choice",
   q:"気体が外部から熱Qを受け取り、外部へ仕事Wをしたとき、内部エネルギー変化ΔUはどれか。",o:["Q+W","Q-W","W-Q","-Q-W"],a:[2],
   e:"気体が外へした仕事をWとする約束では、ΔU=Q-W。"},
  {id:"phy-9",subject:"physics",c:3,s:"波",n:9,d:"A",type:"choice",
   q:"波の速さv、振動数f、波長λの関係として正しいものを選びなさい。",o:["v=fλ","v=f/λ","v=λ/f","v=f+λ"],a:[1],
   e:"1周期で1波長進むので v=fλ。"},
  {id:"phy-10",subject:"physics",c:4,s:"電場",n:10,d:"B",type:"tf",
   q:"正の試験電荷が受ける力の向きが、その点での電場の向きである。",a:true,
   e:"電場の向きは、正の試験電荷に働く力の向きで定義される。"},
  {id:"phy-11",subject:"physics",c:4,s:"コンデンサー",n:11,d:"B",type:"input",
   q:"電気容量C、電圧V、電気量Qの関係を Q= の形で答えなさい。",answers:["CV","C V","C×V","C*V"],aText:"CV",
   e:"コンデンサーでは Q=CV。"},
  {id:"phy-12",subject:"physics",c:5,s:"光電効果",n:12,d:"C",type:"tf",
   q:"光電効果では、入射光の振動数がしきい振動数より低ければ、光を強くしても光電子は放出されない。",a:true,
   e:"1個の光子のエネルギーhfが仕事関数を超える必要がある。強度を上げても光子1個あたりのエネルギーは増えない。"},

  /* ---------- 地学 ---------- */
  {id:"ear-1",subject:"earth",c:1,s:"地球内部",n:1,d:"A",type:"tf",
   q:"地球の外核は主に液体で、内核は主に固体である。",a:true,
   e:"外核は液体、内核は高圧のため固体と考えられている。"},
  {id:"ear-2",subject:"earth",c:1,s:"地震波",n:2,d:"A",type:"choice",
   q:"液体中を伝わらない地震波はどれか。",o:["P波","S波","表面波","どれも伝わる"],a:[2],
   e:"S波はせん断変形を伝える波なので液体中を伝わらない。"},
  {id:"ear-3",subject:"earth",c:1,s:"プレート",n:3,d:"B",type:"tf",
   q:"海洋プレートは、一般に中央海嶺付近で形成され、海溝付近で沈み込む。",a:true,
   e:"海洋底拡大により海嶺で形成され、収束境界の海溝で沈み込む。"},
  {id:"ear-4",subject:"earth",c:2,s:"地層",n:4,d:"A",type:"choice",
   q:"未変形の地層で、一般に下位ほど古いとする原理はどれか。",o:["地層累重の法則","斉一説","相対性原理","パスカルの原理"],a:[1],
   e:"地層累重の法則では、通常は下の地層ほど古い。"},
  {id:"ear-5",subject:"earth",c:2,s:"示準化石",n:5,d:"B",type:"tf",
   q:"示準化石は、地層が堆積した年代を推定する手がかりになる。",a:true,
   e:"生存期間が比較的短く広く分布した生物の化石は、年代対比に有効。"},
  {id:"ear-6",subject:"earth",c:3,s:"大気",n:6,d:"A",type:"choice",
   q:"対流圏では高度が上がるにつれて、気温は一般にどうなるか。",o:["上がる","下がる","一定","必ず0℃になる"],a:[2],
   e:"対流圏では高度とともに気温は一般に低下する。"},
  {id:"ear-7",subject:"earth",c:3,s:"コリオリの力",n:7,d:"B",type:"choice",
   q:"北半球で運動する空気は、進行方向に対してどちら向きに曲げられるか。",o:["右","左","上","下"],a:[1],
   e:"北半球ではコリオリの力により進行方向の右向きに偏向する。"},
  {id:"ear-8",subject:"earth",c:3,s:"海洋",n:8,d:"B",type:"tf",
   q:"黒潮は日本の南岸付近を流れる暖流である。",a:true,
   e:"黒潮は北太平洋西部を北上する代表的な暖流。"},
  {id:"ear-9",subject:"earth",c:4,s:"恒星",n:9,d:"A",type:"choice",
   q:"恒星の表面温度が高いほど、一般に何色寄りに見えるか。",o:["赤","青白","緑","黒"],a:[2],
   e:"高温の恒星ほど青白く、低温の恒星ほど赤く見える。"},
  {id:"ear-10",subject:"earth",c:4,s:"太陽系",n:10,d:"A",type:"input",
   q:"太陽系で最も大きい惑星を日本語で答えなさい。",answers:["木星"],aText:"木星",
   e:"太陽系最大の惑星は木星。"},

  /* ---------- 古典 ---------- */
  {id:"cla-1",subject:"classics",c:1,s:"古文単語",n:1,d:"A",type:"choice",
   q:"古文単語『をかし』の代表的な意味として最も適切なものを選びなさい。",o:["趣がある・すばらしい","恐ろしい","腹立たしい","眠い"],a:[1],
   e:"『をかし』は、趣がある・すばらしい・おもしろいなどの意味。"},
  {id:"cla-2",subject:"classics",c:1,s:"古文単語",n:2,d:"A",type:"input",
   q:"古文単語『いみじ』の代表的な意味を1つ答えなさい。",answers:["とても","たいそう","はなはだしい","すばらしい","ひどい"],aText:"とても／たいそう など",
   e:"『いみじ』は程度が甚だしいことを表し、文脈により『とてもすばらしい』『ひどい』などになる。"},
  {id:"cla-3",subject:"classics",c:2,s:"助動詞",n:3,d:"A",type:"choice",
   q:"助動詞『けり』の代表的な意味の組として適切なものを選びなさい。",o:["過去・詠嘆","推量・意志","打消・禁止","断定・存在"],a:[1],
   e:"『けり』は過去と詠嘆が中心。"},
  {id:"cla-4",subject:"classics",c:2,s:"助動詞",n:4,d:"B",type:"tf",
   q:"助動詞『まじ』には、打消推量・打消意志・不可能などの意味がある。",a:true,
   e:"『まじ』は否定的意味を持ち、打消推量・打消意志・不可能・禁止・当然の打消・不適当など。"},
  {id:"cla-5",subject:"classics",c:2,s:"助動詞",n:5,d:"B",type:"choice",
   q:"助動詞『む』が一人称主語で使われるとき、代表的に何を表すか。",o:["意志","過去","断定","打消"],a:[1],
   e:"一人称主語では意志、二人称では勧誘・適当、三人称では推量となることが多い。"},
  {id:"cla-6",subject:"classics",c:2,s:"係り結び",n:6,d:"A",type:"choice",
   q:"係助詞『ぞ・なむ・や・か』の結びは何形か。",o:["連体形","已然形","終止形","命令形"],a:[1],
   e:"ぞ・なむ・や・か → 連体形。こそ → 已然形。"},
  {id:"cla-7",subject:"classics",c:2,s:"係り結び",n:7,d:"A",type:"input",
   q:"係助詞『こそ』の結びの活用形を答えなさい。",answers:["已然形"],aText:"已然形",
   e:"『こそ』の結びは已然形。"},
  {id:"cla-8",subject:"classics",c:3,s:"敬語",n:8,d:"B",type:"choice",
   q:"尊敬語は、基本的に誰の動作を高める敬語か。",o:["動作主","話し手","聞き手","必ず作者"],a:[1],
   e:"尊敬語は動作主を高める。謙譲語は動作の受け手側を高める。"},
  {id:"cla-9",subject:"classics",c:3,s:"敬語",n:9,d:"B",type:"tf",
   q:"謙譲語は、話し手側の動作を低めることで、その動作が向かう相手を高める。",a:true,
   e:"謙譲語の基本構造。誰から誰への動作かを見る。"},
  {id:"cla-10",subject:"classics",c:4,s:"主語把握",n:10,d:"B",type:"tf",
   q:"古文では主語が省略されることが多いため、敬語や接続助詞も主語判断の手がかりになる。",a:true,
   e:"古文読解では敬語の方向、接続、人物関係などを使って主語を補う。"},
  {id:"cla-11",subject:"classics",c:1,s:"古文単語",n:11,d:"A",type:"choice",
   q:"古文単語『あはれなり』の意味として最も近いものを選びなさい。",o:["しみじみと心を動かされる","非常に速い","腹が減る","明るく輝く"],a:[1],
   e:"『あはれ』は、しみじみとした感動や情趣を表す。"},
  {id:"cla-12",subject:"classics",c:2,s:"助動詞",n:12,d:"B",type:"choice",
   q:"伝聞・推定の助動詞『なり』が接続する形として基本的に正しいものはどれか。",o:["終止形","未然形","連用形","命令形"],a:[1],
   e:"伝聞・推定の『なり』は原則として終止形接続。ラ変型には連体形接続。"},

  /* ---------- ドイツ語：基本動詞200 ---------- */
  {"id":"ger-v001","subject":"german","c":1,"s":"基本動詞200","n":1,"d":"A","type":"input","q":"基本動詞 No.1：4を尊敬する／4を尊重する。auf 4 achten：4に注意する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["achten"],"caseSensitive":false,"aText":"achten","e":"achten：4を尊敬する／4を尊重する。auf 4 achten：4に注意する"},
  {"id":"ger-v002","subject":"german","c":1,"s":"基本動詞200","n":2,"d":"A","type":"input","q":"基本動詞 No.2：4を変える。sich ändern：変わる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["ändern"],"caseSensitive":false,"aText":"ändern","e":"ändern：4を変える。sich ändern：変わる"},
  {"id":"ger-v003","subject":"german","c":1,"s":"基本動詞200","n":3,"d":"A","type":"input","q":"基本動詞 No.3：始まる／4を始める。mit 3 anfangen：3を始める、3から始める に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["anfangen"],"caseSensitive":false,"aText":"anfangen","e":"anfangen：始まる／4を始める。mit 3 anfangen：3を始める、3から始める"},
  {"id":"ger-v004","subject":"german","c":1,"s":"基本動詞200","n":4,"d":"A","type":"input","q":"基本動詞 No.4：答える。auf 4 antworten：4に答える に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["antworten"],"caseSensitive":false,"aText":"antworten","e":"antworten：答える。auf 4 antworten：4に答える"},
  {"id":"ger-v005","subject":"german","c":1,"s":"基本動詞200","n":5,"d":"A","type":"input","q":"基本動詞 No.5：働く。an 3 arbeiten：3に従事する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["arbeiten"],"caseSensitive":false,"aText":"arbeiten","e":"arbeiten：働く。an 3 arbeiten：3に従事する"},
  {"id":"ger-v006","subject":"german","c":1,"s":"基本動詞200","n":6,"d":"A","type":"input","q":"基本動詞 No.6：呼吸する／4を吸い込む に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["atmen"],"caseSensitive":false,"aText":"atmen","e":"atmen：呼吸する／4を吸い込む"},
  {"id":"ger-v007","subject":"german","c":1,"s":"基本動詞200","n":7,"d":"A","type":"input","q":"基本動詞 No.7：昇る／開く に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["aufgehen"],"caseSensitive":false,"aText":"aufgehen","e":"aufgehen：昇る／開く"},
  {"id":"ger-v008","subject":"german","c":1,"s":"基本動詞200","n":8,"d":"A","type":"input","q":"基本動詞 No.8：止む。mit 3 aufhören：3を止める に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["aufhören"],"caseSensitive":false,"aText":"aufhören","e":"aufhören：止む。mit 3 aufhören：3を止める"},
  {"id":"ger-v009","subject":"german","c":1,"s":"基本動詞200","n":9,"d":"A","type":"input","q":"基本動詞 No.9：4を開く／4を開ける に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["aufmachen"],"caseSensitive":false,"aText":"aufmachen","e":"aufmachen：4を開く／4を開ける"},
  {"id":"ger-v010","subject":"german","c":1,"s":"基本動詞200","n":10,"d":"A","type":"input","q":"基本動詞 No.10：立ち上がる／起きる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["aufstehen"],"caseSensitive":false,"aText":"aufstehen","e":"aufstehen：立ち上がる／起きる"},
  {"id":"ger-v011","subject":"german","c":1,"s":"基本動詞200","n":11,"d":"A","type":"input","q":"基本動詞 No.11：〜のように見える に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["aussehen"],"caseSensitive":false,"aText":"aussehen","e":"aussehen：〜のように見える"},
  {"id":"ger-v012","subject":"german","c":1,"s":"基本動詞200","n":12,"d":"A","type":"input","q":"基本動詞 No.12：4を建てる／4をつくる。an 3 bauen：3の建設に従事する。auf 4 bauen：4を頼りにする に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["bauen"],"caseSensitive":false,"aText":"bauen","e":"bauen：4を建てる／4をつくる。an 3 bauen：3の建設に従事する。auf 4 bauen：4を頼りにする"},
  {"id":"ger-v013","subject":"german","c":1,"s":"基本動詞200","n":13,"d":"A","type":"input","q":"基本動詞 No.13：4を意味する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["bedeuten"],"caseSensitive":false,"aText":"bedeuten","e":"bedeuten：4を意味する"},
  {"id":"ger-v014","subject":"german","c":1,"s":"基本動詞200","n":14,"d":"A","type":"input","q":"基本動詞 No.14：3に出会う に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["begegnen"],"caseSensitive":false,"aText":"begegnen","e":"begegnen：3に出会う"},
  {"id":"ger-v015","subject":"german","c":1,"s":"基本動詞200","n":15,"d":"A","type":"input","q":"基本動詞 No.15：始まる／4を始める。mit 3 beginnen：3を始める、3から始まる。zu 不定詞 beginnen：〜し始める に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["beginnen"],"caseSensitive":false,"aText":"beginnen","e":"beginnen：始まる／4を始める。mit 3 beginnen：3を始める、3から始まる。zu 不定詞 beginnen：〜し始める"},
  {"id":"ger-v016","subject":"german","c":1,"s":"基本動詞200","n":16,"d":"A","type":"input","q":"基本動詞 No.16：4に伴う に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["begleiten"],"caseSensitive":false,"aText":"begleiten","e":"begleiten：4に伴う"},
  {"id":"ger-v017","subject":"german","c":1,"s":"基本動詞200","n":17,"d":"A","type":"input","q":"基本動詞 No.17：4を取り扱う に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["behandeln"],"caseSensitive":false,"aText":"behandeln","e":"behandeln：4を取り扱う"},
  {"id":"ger-v018","subject":"german","c":1,"s":"基本動詞200","n":18,"d":"A","type":"input","q":"基本動詞 No.18：4をもらう／4を得る に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["bekommen"],"caseSensitive":false,"aText":"bekommen","e":"bekommen：4をもらう／4を得る"},
  {"id":"ger-v019","subject":"german","c":1,"s":"基本動詞200","n":19,"d":"A","type":"input","q":"基本動詞 No.19：4に気づく に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["bemerken"],"caseSensitive":false,"aText":"bemerken","e":"bemerken：4に気づく"},
  {"id":"ger-v020","subject":"german","c":1,"s":"基本動詞200","n":20,"d":"A","type":"input","q":"基本動詞 No.20：4を訪れる／4に行く に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["besuchen"],"caseSensitive":false,"aText":"besuchen","e":"besuchen：4を訪れる／4に行く"},
  {"id":"ger-v021","subject":"german","c":1,"s":"基本動詞200","n":21,"d":"A","type":"input","q":"基本動詞 No.21：祈る に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["beten"],"caseSensitive":false,"aText":"beten","e":"beten：祈る"},
  {"id":"ger-v022","subject":"german","c":1,"s":"基本動詞200","n":22,"d":"A","type":"input","q":"基本動詞 No.22：4を動かす。sich bewegen：動く。4 zu 3 bewegen：4に3させる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["bewegen"],"caseSensitive":false,"aText":"bewegen","e":"bewegen：4を動かす。sich bewegen：動く。4 zu 3 bewegen：4に3させる"},
  {"id":"ger-v023","subject":"german","c":1,"s":"基本動詞200","n":23,"d":"A","type":"input","q":"基本動詞 No.23：4を支払う に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["bezahlen"],"caseSensitive":false,"aText":"bezahlen","e":"bezahlen：4を支払う"},
  {"id":"ger-v024","subject":"german","c":1,"s":"基本動詞200","n":24,"d":"A","type":"input","q":"基本動詞 No.24：4を形成する。sich bilden：形成される に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["bilden"],"caseSensitive":false,"aText":"bilden","e":"bilden：4を形成する。sich bilden：形成される"},
  {"id":"ger-v025","subject":"german","c":1,"s":"基本動詞200","n":25,"d":"A","type":"input","q":"基本動詞 No.25：4を結ぶ。4 an 4 binden：4を4に結び付ける に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["binden"],"caseSensitive":false,"aText":"binden","e":"binden：4を結ぶ。4 an 4 binden：4を4に結び付ける"},
  {"id":"ger-v026","subject":"german","c":1,"s":"基本動詞200","n":26,"d":"A","type":"input","q":"基本動詞 No.26：4を頼む。4 um 4 bitten：4に4を頼む に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["bitten"],"caseSensitive":false,"aText":"bitten","e":"bitten：4を頼む。4 um 4 bitten：4に4を頼む"},
  {"id":"ger-v027","subject":"german","c":1,"s":"基本動詞200","n":27,"d":"A","type":"input","q":"基本動詞 No.27：留まる／残る／1のままである に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["bleiben"],"caseSensitive":false,"aText":"bleiben","e":"bleiben：留まる／残る／1のままである"},
  {"id":"ger-v028","subject":"german","c":1,"s":"基本動詞200","n":28,"d":"A","type":"input","q":"基本動詞 No.28：見る に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["blicken"],"caseSensitive":false,"aText":"blicken","e":"blicken：見る"},
  {"id":"ger-v029","subject":"german","c":1,"s":"基本動詞200","n":29,"d":"A","type":"input","q":"基本動詞 No.29：咲いている／栄えている に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["blühen"],"caseSensitive":false,"aText":"blühen","e":"blühen：咲いている／栄えている"},
  {"id":"ger-v030","subject":"german","c":1,"s":"基本動詞200","n":30,"d":"A","type":"input","q":"基本動詞 No.30：4を必要とする。nicht zu 不定詞 brauchen：〜する必要がない。nur zu 不定詞 brauchen：〜しさえすればよい に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["brauchen"],"caseSensitive":false,"aText":"brauchen","e":"brauchen：4を必要とする。nicht zu 不定詞 brauchen：〜する必要がない。nur zu 不定詞 brauchen：〜しさえすればよい"},
  {"id":"ger-v031","subject":"german","c":1,"s":"基本動詞200","n":31,"d":"A","type":"input","q":"基本動詞 No.31：4を折る／4を割る／4を破る。折れる／割れる。aus 3 brechen：3から現れる。mit 3 brechen：3と絶交する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["brechen"],"caseSensitive":false,"aText":"brechen","e":"brechen：4を折る／4を割る／4を破る。折れる／割れる。aus 3 brechen：3から現れる。mit 3 brechen：3と絶交する"},
  {"id":"ger-v032","subject":"german","c":1,"s":"基本動詞200","n":32,"d":"A","type":"input","q":"基本動詞 No.32：燃える／4を燃やす に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["brennen"],"caseSensitive":false,"aText":"brennen","e":"brennen：燃える／4を燃やす"},
  {"id":"ger-v033","subject":"german","c":1,"s":"基本動詞200","n":33,"d":"A","type":"input","q":"基本動詞 No.33：4を持ってくる／4をもたらす に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["bringen"],"caseSensitive":false,"aText":"bringen","e":"bringen：4を持ってくる／4をもたらす"},
  {"id":"ger-v034","subject":"german","c":1,"s":"基本動詞200","n":34,"d":"A","type":"input","q":"基本動詞 No.34：3に感謝する。3 für 4 danken：3に4のことで感謝する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["danken"],"caseSensitive":false,"aText":"danken","e":"danken：3に感謝する。3 für 4 danken：3に4のことで感謝する"},
  {"id":"ger-v035","subject":"german","c":1,"s":"基本動詞200","n":35,"d":"A","type":"input","q":"基本動詞 No.35：続く に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["dauern"],"caseSensitive":false,"aText":"dauern","e":"dauern：続く"},
  {"id":"ger-v036","subject":"german","c":1,"s":"基本動詞200","n":36,"d":"A","type":"input","q":"基本動詞 No.36：4を覆う。4 mit 3 decken：4を3で覆う に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["decken"],"caseSensitive":false,"aText":"decken","e":"decken：4を覆う。4 mit 3 decken：4を3で覆う"},
  {"id":"ger-v037","subject":"german","c":1,"s":"基本動詞200","n":37,"d":"A","type":"input","q":"基本動詞 No.37：考える。an 4 denken：4（のこと）を考える。über 4 denken：4について考える に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["denken"],"caseSensitive":false,"aText":"denken","e":"denken：考える。an 4 denken：4（のこと）を考える。über 4 denken：4について考える"},
  {"id":"ger-v038","subject":"german","c":1,"s":"基本動詞200","n":38,"d":"A","type":"input","q":"基本動詞 No.38：3に仕える／3に役立つ。als 1 dienen：1として役立つ、1として使われる。zu 3 dienen：3に役立つ に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["dienen"],"caseSensitive":false,"aText":"dienen","e":"dienen：3に仕える／3に役立つ。als 1 dienen：1として役立つ、1として使われる。zu 3 dienen：3に役立つ"},
  {"id":"ger-v039","subject":"german","c":1,"s":"基本動詞200","n":39,"d":"A","type":"input","q":"基本動詞 No.39：4を回す。sich drehen：回る。es dreht sich um 4：4が問題である に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["drehen"],"caseSensitive":false,"aText":"drehen","e":"drehen：4を回す。sich drehen：回る。es dreht sich um 4：4が問題である"},
  {"id":"ger-v040","subject":"german","c":1,"s":"基本動詞200","n":40,"d":"A","type":"input","q":"基本動詞 No.40：4を押す／4を苦しめる。auf 4 drücken：4を押す に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["drücken"],"caseSensitive":false,"aText":"drücken","e":"drücken：4を押す／4を苦しめる。auf 4 drücken：4を押す"},
  {"id":"ger-v041","subject":"german","c":1,"s":"基本動詞200","n":41,"d":"A","type":"input","q":"基本動詞 No.41：4を尊敬する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["ehren"],"caseSensitive":false,"aText":"ehren","e":"ehren：4を尊敬する"},
  {"id":"ger-v042","subject":"german","c":1,"s":"基本動詞200","n":42,"d":"A","type":"input","q":"基本動詞 No.42：急ぐ に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["eilen"],"caseSensitive":false,"aText":"eilen","e":"eilen：急ぐ"},
  {"id":"ger-v043","subject":"german","c":1,"s":"基本動詞200","n":43,"d":"A","type":"input","q":"基本動詞 No.43：終わる。mit 3 enden：3で終わる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["enden"],"caseSensitive":false,"aText":"enden","e":"enden：終わる。mit 3 enden：3で終わる"},
  {"id":"ger-v044","subject":"german","c":1,"s":"基本動詞200","n":44,"d":"A","type":"input","q":"基本動詞 No.44：4を発見する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["entdecken"],"caseSensitive":false,"aText":"entdecken","e":"entdecken：4を発見する"},
  {"id":"ger-v045","subject":"german","c":1,"s":"基本動詞200","n":45,"d":"A","type":"input","q":"基本動詞 No.45：4を発展（発達）させる。sich entwickeln：発展（発達）する。sich zu 3 entwickeln：（発展して）3になる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["entwickeln"],"caseSensitive":false,"aText":"entwickeln","e":"entwickeln：4を発展（発達）させる。sich entwickeln：発展（発達）する。sich zu 3 entwickeln：（発展して）3になる"},
  {"id":"ger-v046","subject":"german","c":1,"s":"基本動詞200","n":46,"d":"A","type":"input","q":"基本動詞 No.46：4を（聞いて）知る／4を経験する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["erfahren"],"caseSensitive":false,"aText":"erfahren","e":"erfahren：4を（聞いて）知る／4を経験する"},
  {"id":"ger-v047","subject":"german","c":1,"s":"基本動詞200","n":47,"d":"A","type":"input","q":"基本動詞 No.47：4を思い出させる。4 an 4 erinnern：4に4を思い出させる。sich an 4 erinnern：4を思い出す に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["erinnern"],"caseSensitive":false,"aText":"erinnern","e":"erinnern：4を思い出させる。4 an 4 erinnern：4に4を思い出させる。sich an 4 erinnern：4を思い出す"},
  {"id":"ger-v048","subject":"german","c":1,"s":"基本動詞200","n":48,"d":"A","type":"input","q":"基本動詞 No.48：4を説明する／4を宣言する／4を表明する。sich erklären：説明される に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["erklären"],"caseSensitive":false,"aText":"erklären","e":"erklären：4を説明する／4を宣言する／4を表明する。sich erklären：説明される"},
  {"id":"ger-v049","subject":"german","c":1,"s":"基本動詞200","n":49,"d":"A","type":"input","q":"基本動詞 No.49：4を許す。sich 4 erlauben：敢えて4をする に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["erlauben"],"caseSensitive":false,"aText":"erlauben","e":"erlauben：4を許す。sich 4 erlauben：敢えて4をする"},
  {"id":"ger-v050","subject":"german","c":1,"s":"基本動詞200","n":50,"d":"A","type":"input","q":"基本動詞 No.50：4を体験する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["erleben"],"caseSensitive":false,"aText":"erleben","e":"erleben：4を体験する"},

  {"id":"ger-v051","subject":"german","c":1,"s":"基本動詞200","n":51,"d":"A","type":"input","q":"基本動詞 No.51：現れる／刊行される／形のように思われる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["erscheinen"],"caseSensitive":false,"aText":"erscheinen","e":"erscheinen：現れる／刊行される／形のように思われる"},
  {"id":"ger-v052","subject":"german","c":1,"s":"基本動詞200","n":52,"d":"A","type":"input","q":"基本動詞 No.52：4を待つ／4を期待する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["erwarten"],"caseSensitive":false,"aText":"erwarten","e":"erwarten：4を待つ／4を期待する"},
  {"id":"ger-v053","subject":"german","c":1,"s":"基本動詞200","n":53,"d":"A","type":"input","q":"基本動詞 No.53：4を食べる／食べる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["essen"],"caseSensitive":false,"aText":"essen","e":"essen：4を食べる／食べる"},
  {"id":"ger-v054","subject":"german","c":1,"s":"基本動詞200","n":54,"d":"A","type":"input","q":"基本動詞 No.54：（乗り物で）行く に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["fahren"],"caseSensitive":false,"aText":"fahren","e":"fahren：（乗り物で）行く"},
  {"id":"ger-v055","subject":"german","c":1,"s":"基本動詞200","n":55,"d":"A","type":"input","q":"基本動詞 No.55：落ちる／倒れる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["fallen"],"caseSensitive":false,"aText":"fallen","e":"fallen：落ちる／倒れる"},
  {"id":"ger-v056","subject":"german","c":1,"s":"基本動詞200","n":56,"d":"A","type":"input","q":"基本動詞 No.56：4を捕らえる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["fangen"],"caseSensitive":false,"aText":"fangen","e":"fangen：4を捕らえる"},
  {"id":"ger-v057","subject":"german","c":1,"s":"基本動詞200","n":57,"d":"A","type":"input","q":"基本動詞 No.57：4を掴む／4を収容する／4を理解する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["fassen"],"caseSensitive":false,"aText":"fassen","e":"fassen：4を掴む／4を収容する／4を理解する"},
  {"id":"ger-v058","subject":"german","c":1,"s":"基本動詞200","n":58,"d":"A","type":"input","q":"基本動詞 No.58：4を見つける／4を得る／4を形と思う に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["finden"],"caseSensitive":false,"aText":"finden","e":"finden：4を見つける／4を得る／4を形と思う"},
  {"id":"ger-v059","subject":"german","c":1,"s":"基本動詞200","n":59,"d":"A","type":"input","q":"基本動詞 No.59：飛ぶ に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["fliegen"],"caseSensitive":false,"aText":"fliegen","e":"fliegen：飛ぶ"},
  {"id":"ger-v060","subject":"german","c":1,"s":"基本動詞200","n":60,"d":"A","type":"input","q":"基本動詞 No.60：流れる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["fließen"],"caseSensitive":false,"aText":"fließen","e":"fließen：流れる"},
  {"id":"ger-v061","subject":"german","c":1,"s":"基本動詞200","n":61,"d":"A","type":"input","q":"基本動詞 No.61：3に従う／auf 4 folgen：4に続く／aus 3 folgen：3から推論される に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["folgen"],"caseSensitive":false,"aText":"folgen","e":"folgen：3に従う／auf 4 folgen：4に続く／aus 3 folgen：3から推論される"},
  {"id":"ger-v062","subject":"german","c":1,"s":"基本動詞200","n":62,"d":"A","type":"input","q":"基本動詞 No.62：4に尋ねる／4 nach 3 fragen：4に3を尋ねる／nach 3 fragen：3（の事）を気にかける に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["fragen"],"caseSensitive":false,"aText":"fragen","e":"fragen：4に尋ねる／4 nach 3 fragen：4に3を尋ねる／nach 3 fragen：3（の事）を気にかける"},
  {"id":"ger-v063","subject":"german","c":1,"s":"基本動詞200","n":63,"d":"A","type":"input","q":"基本動詞 No.63：4を喜ばせる／sich an 3 freuen：3を楽しむ／sich auf 4 freuen：4を楽しみにしている／sich über 4 freuen：4を喜ぶ に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["freuen"],"caseSensitive":false,"aText":"freuen","e":"freuen：4を喜ばせる／sich an 3 freuen：3を楽しむ／sich auf 4 freuen：4を楽しみにしている／sich über 4 freuen：4を喜ぶ"},
  {"id":"ger-v064","subject":"german","c":1,"s":"基本動詞200","n":64,"d":"A","type":"input","q":"基本動詞 No.64：4を感じる／sich 形 fühlen：（自分を）形と感じる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["fühlen"],"caseSensitive":false,"aText":"fühlen","e":"fühlen：4を感じる／sich 形 fühlen：（自分を）形と感じる"},
  {"id":"ger-v065","subject":"german","c":1,"s":"基本動詞200","n":65,"d":"A","type":"input","q":"基本動詞 No.65：4を導く／zu 3 führen：3に至る／zu 3 führen：3をもたらす に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["führen"],"caseSensitive":false,"aText":"führen","e":"führen：4を導く／zu 3 führen：3に至る／zu 3 führen：3をもたらす"},
  {"id":"ger-v066","subject":"german","c":1,"s":"基本動詞200","n":66,"d":"A","type":"input","q":"基本動詞 No.66：4を満たす／4 mit 3 füllen：4を3で満たす に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["füllen"],"caseSensitive":false,"aText":"füllen","e":"füllen：4を満たす／4 mit 3 füllen：4を3で満たす"},
  {"id":"ger-v067","subject":"german","c":1,"s":"基本動詞200","n":67,"d":"A","type":"input","q":"基本動詞 No.67：4を恐れる／sich vor 3 fürchten：3を恐れる／für（um）4 fürchten：4（の事）を心配する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["fürchten"],"caseSensitive":false,"aText":"fürchten","e":"fürchten：4を恐れる／sich vor 3 fürchten：3を恐れる／für（um）4 fürchten：4（の事）を心配する"},
  {"id":"ger-v068","subject":"german","c":1,"s":"基本動詞200","n":68,"d":"A","type":"input","q":"基本動詞 No.68：3に4を与える／es gibt 4：4が存在する／es gibt 4：4が起こる／zu 不定詞 geben：不定詞させる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["geben"],"caseSensitive":false,"aText":"geben","e":"geben：3に4を与える／es gibt 4：4が存在する／es gibt 4：4が起こる／zu 不定詞 geben：不定詞させる"},
  {"id":"ger-v069","subject":"german","c":1,"s":"基本動詞200","n":69,"d":"A","type":"input","q":"基本動詞 No.69：3に気に入る に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["gefallen"],"caseSensitive":false,"aText":"gefallen","e":"gefallen：3に気に入る"},
  {"id":"ger-v070","subject":"german","c":1,"s":"基本動詞200","n":70,"d":"A","type":"input","q":"基本動詞 No.70：行く／an 4 gehen：4に取りかかる／不定詞 gehen：不定詞しに行く／es geht um 4：4が問題である に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["gehen"],"caseSensitive":false,"aText":"gehen","e":"gehen：行く／an 4 gehen：4に取りかかる／不定詞 gehen：不定詞しに行く／es geht um 4：4が問題である"},
  {"id":"ger-v071","subject":"german","c":1,"s":"基本動詞200","n":71,"d":"A","type":"input","q":"基本動詞 No.71：3のものである／zu 3 gehören：3の一部である／zu 3 gehören：3のために必要である／zu 3 gehören：3にふさわしい／in 4 gehören：4に入れられるべきである に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["gehören"],"caseSensitive":false,"aText":"gehören","e":"gehören：3のものである／zu 3 gehören：3の一部である／zu 3 gehören：3のために必要である／zu 3 gehören：3にふさわしい／in 4 gehören：4に入れられるべきである"},
  {"id":"ger-v072","subject":"german","c":1,"s":"基本動詞200","n":72,"d":"A","type":"input","q":"基本動詞 No.72：4と思う／4を信じる／3 glauben：3を信じる／an 4 glauben：4を信じる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["glauben"],"caseSensitive":false,"aText":"glauben","e":"glauben：4と思う／4を信じる／3 glauben：3を信じる／an 4 glauben：4を信じる"},
  {"id":"ger-v073","subject":"german","c":1,"s":"基本動詞200","n":73,"d":"A","type":"input","q":"基本動詞 No.73：4を掴む／nach 3 greifen：3に手を伸ばす／zu 3 greifen：3を手にとる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["greifen"],"caseSensitive":false,"aText":"greifen","e":"greifen：4を掴む／nach 3 greifen：3に手を伸ばす／zu 3 greifen：3を手にとる"},
  {"id":"ger-v074","subject":"german","c":1,"s":"基本動詞200","n":74,"d":"A","type":"input","q":"基本動詞 No.74：4に挨拶する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["grüßen"],"caseSensitive":false,"aText":"grüßen","e":"grüßen：4に挨拶する"},
  {"id":"ger-v075","subject":"german","c":1,"s":"基本動詞200","n":75,"d":"A","type":"input","q":"基本動詞 No.75：4を持っている／es leicht haben：楽である／es mit 3 zu tun haben：3に関わる／zu 不定詞 haben：不定詞しなければならない／zu 不定詞 haben：不定詞し得る に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["haben"],"caseSensitive":false,"aText":"haben","e":"haben：4を持っている／es leicht haben：楽である／es mit 3 zu tun haben：3に関わる／zu 不定詞 haben：不定詞しなければならない／zu 不定詞 haben：不定詞し得る"},
  {"id":"ger-v076","subject":"german","c":1,"s":"基本動詞200","n":76,"d":"A","type":"input","q":"基本動詞 No.76：4を（手に）持っている／4を守る、4を保つ／4を行う／sich halten：持ちこたえる／halten：止まる／4 für 4 halten：4を4と思う に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["halten"],"caseSensitive":false,"aText":"halten","e":"halten：4を（手に）持っている／4を守る、4を保つ／4を行う／sich halten：持ちこたえる／halten：止まる／4 für 4 halten：4を4と思う"},
  {"id":"ger-v077","subject":"german","c":1,"s":"基本動詞200","n":77,"d":"A","type":"input","q":"基本動詞 No.77：行動する／mit 3 handeln：3を商う／von 3（über 4）handeln：3（4）を扱う／es handelt sich um 4：4が問題である に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["handeln"],"caseSensitive":false,"aText":"handeln","e":"handeln：行動する／mit 3 handeln：3を商う／von 3（über 4）handeln：3（4）を扱う／es handelt sich um 4：4が問題である"},
  {"id":"ger-v078","subject":"german","c":1,"s":"基本動詞200","n":78,"d":"A","type":"input","q":"基本動詞 No.78：4を掛ける／4 an 4 hängen：4を4に掛ける／an 3 hängen：3に掛っている に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["hängen"],"caseSensitive":false,"aText":"hängen","e":"hängen：4を掛ける／4 an 4 hängen：4を4に掛ける／an 3 hängen：3に掛っている"},
  {"id":"ger-v079","subject":"german","c":1,"s":"基本動詞200","n":79,"d":"A","type":"input","q":"基本動詞 No.79：4を憎む、4を嫌う に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["hassen"],"caseSensitive":false,"aText":"hassen","e":"hassen：4を憎む、4を嫌う"},
  {"id":"ger-v080","subject":"german","c":1,"s":"基本動詞200","n":80,"d":"A","type":"input","q":"基本動詞 No.80：4と結婚する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["heiraten"],"caseSensitive":false,"aText":"heiraten","e":"heiraten：4と結婚する"},
  {"id":"ger-v081","subject":"german","c":1,"s":"基本動詞200","n":81,"d":"A","type":"input","q":"基本動詞 No.81：1という名前である／1という意味である に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["heißen"],"caseSensitive":false,"aText":"heißen","e":"heißen：1という名前である／1という意味である"},
  {"id":"ger-v082","subject":"german","c":1,"s":"基本動詞200","n":82,"d":"A","type":"input","q":"基本動詞 No.82：3を助ける／3に役立つ／3 bei 3 helfen：3の3を助ける に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["helfen"],"caseSensitive":false,"aText":"helfen","e":"helfen：3を助ける／3に役立つ／3 bei 3 helfen：3の3を助ける"},
  {"id":"ger-v083","subject":"german","c":1,"s":"基本動詞200","n":83,"d":"A","type":"input","q":"基本動詞 No.83：支配する／über 4 herrschen：4を支配する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["herrschen"],"caseSensitive":false,"aText":"herrschen","e":"herrschen：支配する／über 4 herrschen：4を支配する"},
  {"id":"ger-v084","subject":"german","c":1,"s":"基本動詞200","n":84,"d":"A","type":"input","q":"基本動詞 No.84：4を妨げる／4 an 3 hindern：4の3を妨げる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["hindern"],"caseSensitive":false,"aText":"hindern","e":"hindern：4を妨げる／4 an 3 hindern：4の3を妨げる"},
  {"id":"ger-v085","subject":"german","c":1,"s":"基本動詞200","n":85,"d":"A","type":"input","q":"基本動詞 No.85：4を望む／auf 4 hoffen：4を期待する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["hoffen"],"caseSensitive":false,"aText":"hoffen","e":"hoffen：4を望む／auf 4 hoffen：4を期待する"},
  {"id":"ger-v086","subject":"german","c":1,"s":"基本動詞200","n":86,"d":"A","type":"input","q":"基本動詞 No.86：4を持ってくる／4を連れてくる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["holen"],"caseSensitive":false,"aText":"holen","e":"holen：4を持ってくる／4を連れてくる"},
  {"id":"ger-v087","subject":"german","c":1,"s":"基本動詞200","n":87,"d":"A","type":"input","q":"基本動詞 No.87：4を聞く／auf 4 hören：4に耳を傾ける に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["hören"],"caseSensitive":false,"aText":"hören","e":"hören：4を聞く／auf 4 hören：4に耳を傾ける"},
  {"id":"ger-v088","subject":"german","c":1,"s":"基本動詞200","n":88,"d":"A","type":"input","q":"基本動詞 No.88：4を狩る／4を追う／nach 3 jagen：3を追い求める に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["jagen"],"caseSensitive":false,"aText":"jagen","e":"jagen：4を狩る／4を追う／nach 3 jagen：3を追い求める"},
  {"id":"ger-v089","subject":"german","c":1,"s":"基本動詞200","n":89,"d":"A","type":"input","q":"基本動詞 No.89：戦う／für 4 kämpfen：4のために戦う／gegen 4 kämpfen：4と戦う／mit 3 kämpfen：3と戦う、3と共に戦う／um 4 kämpfen：4を得るために戦う に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["kämpfen"],"caseSensitive":false,"aText":"kämpfen","e":"kämpfen：戦う／für 4 kämpfen：4のために戦う／gegen 4 kämpfen：4と戦う／mit 3 kämpfen：3と戦う、3と共に戦う／um 4 kämpfen：4を得るために戦う"},
  {"id":"ger-v090","subject":"german","c":1,"s":"基本動詞200","n":90,"d":"A","type":"input","q":"基本動詞 No.90：4を買う に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["kaufen"],"caseSensitive":false,"aText":"kaufen","e":"kaufen：4を買う"},
  {"id":"ger-v091","subject":"german","c":1,"s":"基本動詞200","n":91,"d":"A","type":"input","q":"基本動詞 No.91：4を知っている に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["kennen"],"caseSensitive":false,"aText":"kennen","e":"kennen：4を知っている"},
  {"id":"ger-v092","subject":"german","c":1,"s":"基本動詞200","n":92,"d":"A","type":"input","q":"基本動詞 No.92：4を（はじめて）知る に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["kennenlernen"],"caseSensitive":false,"aText":"kennenlernen","e":"kennenlernen：4を（はじめて）知る"},
  {"id":"ger-v093","subject":"german","c":1,"s":"基本動詞200","n":93,"d":"A","type":"input","q":"基本動詞 No.93：叩く／4を叩く／an 4 klopfen：4を叩く に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["klopfen"],"caseSensitive":false,"aText":"klopfen","e":"klopfen：叩く／4を叩く／an 4 klopfen：4を叩く"},
  {"id":"ger-v094","subject":"german","c":1,"s":"基本動詞200","n":94,"d":"A","type":"input","q":"基本動詞 No.94：4を煮る／4を沸かす／4を料理する／煮える／沸く／料理をする に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["kochen"],"caseSensitive":false,"aText":"kochen","e":"kochen：4を煮る／4を沸かす／4を料理する／煮える／沸く／料理をする"},
  {"id":"ger-v095","subject":"german","c":1,"s":"基本動詞200","n":95,"d":"A","type":"input","q":"基本動詞 No.95：来る／生じる／in 4 kommen：4に入る／von 3 kommen：3に由来する／zu 3 kommen：3に至る／zu 3 kommen：3を手に入れる／es kommt zu 3：3になる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["kommen"],"caseSensitive":false,"aText":"kommen","e":"kommen：来る／生じる／in 4 kommen：4に入る／von 3 kommen：3に由来する／zu 3 kommen：3に至る／zu 3 kommen：3を手に入れる／es kommt zu 3：3になる"},
  {"id":"ger-v096","subject":"german","c":1,"s":"基本動詞200","n":96,"d":"A","type":"input","q":"基本動詞 No.96：（費用、労力が）かかる／4を要する／4を失わせる／4を味わう に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["kosten"],"caseSensitive":false,"aText":"kosten","e":"kosten：（費用、労力が）かかる／4を要する／4を失わせる／4を味わう"},
  {"id":"ger-v097","subject":"german","c":1,"s":"基本動詞200","n":97,"d":"A","type":"input","q":"基本動詞 No.97：微笑む／über 4 lächeln：4を冷笑する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["lächeln"],"caseSensitive":false,"aText":"lächeln","e":"lächeln：微笑む／über 4 lächeln：4を冷笑する"},
  {"id":"ger-v098","subject":"german","c":1,"s":"基本動詞200","n":98,"d":"A","type":"input","q":"基本動詞 No.98：笑う／über 4 lachen：4を嘲笑する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["lachen"],"caseSensitive":false,"aText":"lachen","e":"lachen：笑う／über 4 lachen：4を嘲笑する"},
  {"id":"ger-v099","subject":"german","c":1,"s":"基本動詞200","n":99,"d":"A","type":"input","q":"基本動詞 No.99：走る／歩く／動く に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["laufen"],"caseSensitive":false,"aText":"laufen","e":"laufen：走る／歩く／動く"},
  {"id":"ger-v100","subject":"german","c":1,"s":"基本動詞200","n":100,"d":"A","type":"input","q":"基本動詞 No.100：生きる／für 4 leben：4のために生きる／von 3 leben：3によって生きる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["leben"],"caseSensitive":false,"aText":"leben","e":"leben：生きる／für 4 leben：4のために生きる／von 3 leben：3によって生きる"},
  {"id":"ger-v101","subject":"german","c":1,"s":"基本動詞200","n":101,"d":"A","type":"input","q":"基本動詞 No.101：4を横たえる／4を置く／sich legen：横たわる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["legen"],"caseSensitive":false,"aText":"legen","e":"legen：4を横たえる／4を置く／sich legen：横たわる"},
  {"id":"ger-v102","subject":"german","c":1,"s":"基本動詞200","n":102,"d":"A","type":"input","q":"基本動詞 No.102：4に4を教える に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["lehren"],"caseSensitive":false,"aText":"lehren","e":"lehren：4に4を教える"},
  {"id":"ger-v103","subject":"german","c":1,"s":"基本動詞200","n":103,"d":"A","type":"input","q":"基本動詞 No.103：4を学ぶ／4を習う／4を覚える に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["lernen"],"caseSensitive":false,"aText":"lernen","e":"lernen：4を学ぶ／4を習う／4を覚える"},
  {"id":"ger-v104","subject":"german","c":1,"s":"基本動詞200","n":104,"d":"A","type":"input","q":"基本動詞 No.104：4を読む に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["lesen"],"caseSensitive":false,"aText":"lesen","e":"lesen：4を読む"},
  {"id":"ger-v105","subject":"german","c":1,"s":"基本動詞200","n":105,"d":"A","type":"input","q":"基本動詞 No.105：4を愛する／4を好む に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["lieben"],"caseSensitive":false,"aText":"lieben","e":"lieben：4を愛する／4を好む"},
  {"id":"ger-v106","subject":"german","c":1,"s":"基本動詞200","n":106,"d":"A","type":"input","q":"基本動詞 No.106：横たわっている／ある／an 3 liegen：3のせいである／an 3 liegen：3次第である に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["liegen"],"caseSensitive":false,"aText":"liegen","e":"liegen：横たわっている／ある／an 3 liegen：3のせいである／an 3 liegen：3次第である"},
  {"id":"ger-v107","subject":"german","c":1,"s":"基本動詞200","n":107,"d":"A","type":"input","q":"基本動詞 No.107：4をほめる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["loben"],"caseSensitive":false,"aText":"loben","e":"loben：4をほめる"},
  {"id":"ger-v108","subject":"german","c":1,"s":"基本動詞200","n":108,"d":"A","type":"input","q":"基本動詞 No.108：4をつくる／4をする／4 形 machen：4を形にする／4 zu 3 machen：4を3にする に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["machen"],"caseSensitive":false,"aText":"machen","e":"machen：4をつくる／4をする／4 形 machen：4を形にする／4 zu 3 machen：4を3にする"},
  {"id":"ger-v109","subject":"german","c":1,"s":"基本動詞200","n":109,"d":"A","type":"input","q":"基本動詞 No.109：4を（絵で）描く に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["malen"],"caseSensitive":false,"aText":"malen","e":"malen：4を（絵で）描く"},
  {"id":"ger-v110","subject":"german","c":1,"s":"基本動詞200","n":110,"d":"A","type":"input","q":"基本動詞 No.110：4と思う／4（の事を）言う に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["meinen"],"caseSensitive":false,"aText":"meinen","e":"meinen：4と思う／4（の事を）言う"},
  {"id":"ger-v111","subject":"german","c":1,"s":"基本動詞200","n":111,"d":"A","type":"input","q":"基本動詞 No.111：4を取る／4 auf sich nehmen：4を引き受ける／4 zu sich nehmen：4を引き取る／4 für 4 nehmen：4を4とみなす に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["nehmen"],"caseSensitive":false,"aText":"nehmen","e":"nehmen：4を取る／4 auf sich nehmen：4を引き受ける／4 zu sich nehmen：4を引き取る／4 für 4 nehmen：4を4とみなす"},
  {"id":"ger-v112","subject":"german","c":1,"s":"基本動詞200","n":112,"d":"A","type":"input","q":"基本動詞 No.112：4を4と名づける／4を4と呼ぶ／4の名を挙げる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["nennen"],"caseSensitive":false,"aText":"nennen","e":"nennen：4を4と名づける／4を4と呼ぶ／4の名を挙げる"},
  {"id":"ger-v113","subject":"german","c":1,"s":"基本動詞200","n":113,"d":"A","type":"input","q":"基本動詞 No.113：4を開ける／4を開く／sich öffnen：開く／sich öffnen：開かれる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["öffnen"],"caseSensitive":false,"aText":"öffnen","e":"öffnen：4を開ける／4を開く／sich öffnen：開く／sich öffnen：開かれる"},
  {"id":"ger-v114","subject":"german","c":1,"s":"基本動詞200","n":114,"d":"A","type":"input","q":"基本動詞 No.114：4を検査する／4を試験する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["prüfen"],"caseSensitive":false,"aText":"prüfen","e":"prüfen：4を検査する／4を試験する"},
  {"id":"ger-v115","subject":"german","c":1,"s":"基本動詞200","n":115,"d":"A","type":"input","q":"基本動詞 No.115：煙草を吸う／煙を出す／4を吸う に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["rauchen"],"caseSensitive":false,"aText":"rauchen","e":"rauchen：煙草を吸う／煙を出す／4を吸う"},
  {"id":"ger-v116","subject":"german","c":1,"s":"基本動詞200","n":116,"d":"A","type":"input","q":"基本動詞 No.116：計算する／auf 4 rechnen：4を当てにする／mit 3 rechnen：3を計算に入れる／zu 3 rechnen：3に数えられる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["rechnen"],"caseSensitive":false,"aText":"rechnen","e":"rechnen：計算する／auf 4 rechnen：4を当てにする／mit 3 rechnen：3を計算に入れる／zu 3 rechnen：3に数えられる"},
  {"id":"ger-v117","subject":"german","c":1,"s":"基本動詞200","n":117,"d":"A","type":"input","q":"基本動詞 No.117：語る／über 4 reden：4について語る に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["reden"],"caseSensitive":false,"aText":"reden","e":"reden：語る／über 4 reden：4について語る"},
  {"id":"ger-v118","subject":"german","c":1,"s":"基本動詞200","n":118,"d":"A","type":"input","q":"基本動詞 No.118：雨が降る に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["regnen"],"caseSensitive":false,"aText":"regnen","e":"regnen：雨が降る"},
  {"id":"ger-v119","subject":"german","c":1,"s":"基本動詞200","n":119,"d":"A","type":"input","q":"基本動詞 No.119：旅行する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["reisen"],"caseSensitive":false,"aText":"reisen","e":"reisen：旅行する"},
  {"id":"ger-v120","subject":"german","c":1,"s":"基本動詞200","n":120,"d":"A","type":"input","q":"基本動詞 No.120：馬に乗る／馬に乗って行く に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["reiten"],"caseSensitive":false,"aText":"reiten","e":"reiten：馬に乗る／馬に乗って行く"},
  {"id":"ger-v121","subject":"german","c":1,"s":"基本動詞200","n":121,"d":"A","type":"input","q":"基本動詞 No.121：4を刺激する／4を怒らせる／4を魅惑する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["reizen"],"caseSensitive":false,"aText":"reizen","e":"reizen：4を刺激する／4を怒らせる／4を魅惑する"},
  {"id":"ger-v122","subject":"german","c":1,"s":"基本動詞200","n":122,"d":"A","type":"input","q":"基本動詞 No.122：4を救う に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["retten"],"caseSensitive":false,"aText":"retten","e":"retten：4を救う"},
  {"id":"ger-v123","subject":"german","c":1,"s":"基本動詞200","n":123,"d":"A","type":"input","q":"基本動詞 No.123：叫ぶ、呼ぶ／nach 3 rufen：3を呼ぶ に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["rufen"],"caseSensitive":false,"aText":"rufen","e":"rufen：叫ぶ、呼ぶ／nach 3 rufen：3を呼ぶ"},
  {"id":"ger-v124","subject":"german","c":1,"s":"基本動詞200","n":124,"d":"A","type":"input","q":"基本動詞 No.124：休む／止まっている に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["ruhen"],"caseSensitive":false,"aText":"ruhen","e":"ruhen：休む／止まっている"},
  {"id":"ger-v125","subject":"german","c":1,"s":"基本動詞200","n":125,"d":"A","type":"input","q":"基本動詞 No.125：4を言う／4と言う に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["sagen"],"caseSensitive":false,"aText":"sagen","e":"sagen：4を言う／4と言う"},
  {"id":"ger-v126","subject":"german","c":1,"s":"基本動詞200","n":126,"d":"A","type":"input","q":"基本動詞 No.126：4を創り出す／4を作り出す／4をなす／働く に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["schaffen"],"caseSensitive":false,"aText":"schaffen","e":"schaffen：4を創り出す／4を作り出す／4をなす／働く"},
  {"id":"ger-v127","subject":"german","c":1,"s":"基本動詞200","n":127,"d":"A","type":"input","q":"基本動詞 No.127：見る／4 schauen：4を見る に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["schauen"],"caseSensitive":false,"aText":"schauen","e":"schauen：見る／4 schauen：4を見る"},
  {"id":"ger-v128","subject":"german","c":1,"s":"基本動詞200","n":128,"d":"A","type":"input","q":"基本動詞 No.128：輝く／zu 不定詞 scheinen：不定詞であるように見える／形 scheinen：形のように見える に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["scheinen"],"caseSensitive":false,"aText":"scheinen","e":"scheinen：輝く／zu 不定詞 scheinen：不定詞であるように見える／形 scheinen：形のように見える"},
  {"id":"ger-v129","subject":"german","c":1,"s":"基本動詞200","n":129,"d":"A","type":"input","q":"基本動詞 No.129：3に4を贈る に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["schenken"],"caseSensitive":false,"aText":"schenken","e":"schenken：3に4を贈る"},
  {"id":"ger-v130","subject":"german","c":1,"s":"基本動詞200","n":130,"d":"A","type":"input","q":"基本動詞 No.130：3に4を送る／4を行かせる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["schicken"],"caseSensitive":false,"aText":"schicken","e":"schicken：3に4を送る／4を行かせる"},
  {"id":"ger-v131","subject":"german","c":1,"s":"基本動詞200","n":131,"d":"A","type":"input","q":"基本動詞 No.131：眠る に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["schlafen"],"caseSensitive":false,"aText":"schlafen","e":"schlafen：眠る"},
  {"id":"ger-v132","subject":"german","c":1,"s":"基本動詞200","n":132,"d":"A","type":"input","q":"基本動詞 No.132：4を打つ に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["schlagen"],"caseSensitive":false,"aText":"schlagen","e":"schlagen：4を打つ"},
  {"id":"ger-v133","subject":"german","c":1,"s":"基本動詞200","n":133,"d":"A","type":"input","q":"基本動詞 No.133：4を閉じる、4を閉める／4を終わらせる／4を結ぶ／4を結論する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["schließen"],"caseSensitive":false,"aText":"schließen","e":"schließen：4を閉じる、4を閉める／4を終わらせる／4を結ぶ／4を結論する"},
  {"id":"ger-v134","subject":"german","c":1,"s":"基本動詞200","n":134,"d":"A","type":"input","q":"基本動詞 No.134：〜の味がする／4を味わう に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["schmecken"],"caseSensitive":false,"aText":"schmecken","e":"schmecken：〜の味がする／4を味わう"},
  {"id":"ger-v135","subject":"german","c":1,"s":"基本動詞200","n":135,"d":"A","type":"input","q":"基本動詞 No.135：4を飾る に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["schmücken"],"caseSensitive":false,"aText":"schmücken","e":"schmücken：4を飾る"},
  {"id":"ger-v136","subject":"german","c":1,"s":"基本動詞200","n":136,"d":"A","type":"input","q":"基本動詞 No.136：4を切る に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["schneiden"],"caseSensitive":false,"aText":"schneiden","e":"schneiden：4を切る"},
  {"id":"ger-v137","subject":"german","c":1,"s":"基本動詞200","n":137,"d":"A","type":"input","q":"基本動詞 No.137：雪が降る に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["schneien"],"caseSensitive":false,"aText":"schneien","e":"schneien：雪が降る"},
  {"id":"ger-v138","subject":"german","c":1,"s":"基本動詞200","n":138,"d":"A","type":"input","q":"基本動詞 No.138：4を書く／書ける に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["schreiben"],"caseSensitive":false,"aText":"schreiben","e":"schreiben：4を書く／書ける"},
  {"id":"ger-v139","subject":"german","c":1,"s":"基本動詞200","n":139,"d":"A","type":"input","q":"基本動詞 No.139：叫ぶ に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["schreien"],"caseSensitive":false,"aText":"schreien","e":"schreien：叫ぶ"},
  {"id":"ger-v140","subject":"german","c":1,"s":"基本動詞200","n":140,"d":"A","type":"input","q":"基本動詞 No.140：黙っている に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["schweigen"],"caseSensitive":false,"aText":"schweigen","e":"schweigen：黙っている"},
  {"id":"ger-v141","subject":"german","c":1,"s":"基本動詞200","n":141,"d":"A","type":"input","q":"基本動詞 No.141：泳ぐ／浮かぶ に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["schwimmen"],"caseSensitive":false,"aText":"schwimmen","e":"schwimmen：泳ぐ／浮かぶ"},
  {"id":"ger-v142","subject":"german","c":1,"s":"基本動詞200","n":142,"d":"A","type":"input","q":"基本動詞 No.142：4を見る／4と会う に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["sehen"],"caseSensitive":false,"aText":"sehen","e":"sehen：4を見る／4と会う"},
  {"id":"ger-v143","subject":"german","c":1,"s":"基本動詞200","n":143,"d":"A","type":"input","q":"基本動詞 No.143：存在する（いる、ある）／1・形 sein：1・形である／zu 不定詞 sein：不定詞され得る／zu 不定詞 sein：不定詞されるべきである に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["sein"],"caseSensitive":false,"aText":"sein","e":"sein：存在する（いる、ある）／1・形 sein：1・形である／zu 不定詞 sein：不定詞され得る／zu 不定詞 sein：不定詞されるべきである"},
  {"id":"ger-v144","subject":"german","c":1,"s":"基本動詞200","n":144,"d":"A","type":"input","q":"基本動詞 No.144：3に4を送る／4を放送する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["senden"],"caseSensitive":false,"aText":"senden","e":"senden：3に4を送る／4を放送する"},
  {"id":"ger-v145","subject":"german","c":1,"s":"基本動詞200","n":145,"d":"A","type":"input","q":"基本動詞 No.145：4を座らせる／4を置く／sich setzen：座る に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["setzen"],"caseSensitive":false,"aText":"setzen","e":"setzen：4を座らせる／4を置く／sich setzen：座る"},
  {"id":"ger-v146","subject":"german","c":1,"s":"基本動詞200","n":146,"d":"A","type":"input","q":"基本動詞 No.146：歌う／4を歌う に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["singen"],"caseSensitive":false,"aText":"singen","e":"singen：歌う／4を歌う"},
  {"id":"ger-v147","subject":"german","c":1,"s":"基本動詞200","n":147,"d":"A","type":"input","q":"基本動詞 No.147：沈む／下がる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["sinken"],"caseSensitive":false,"aText":"sinken","e":"sinken：沈む／下がる"},
  {"id":"ger-v148","subject":"german","c":1,"s":"基本動詞200","n":148,"d":"A","type":"input","q":"基本動詞 No.148：座っている に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["sitzen"],"caseSensitive":false,"aText":"sitzen","e":"sitzen：座っている"},
  {"id":"ger-v149","subject":"german","c":1,"s":"基本動詞200","n":149,"d":"A","type":"input","q":"基本動詞 No.149：心配する／für 4 sorgen：4を心配する／für 4 sorgen：4を調達する／für 4 sorgen：4を引き起こす／sich um 4 sorgen：4を心配する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["sorgen"],"caseSensitive":false,"aText":"sorgen","e":"sorgen：心配する／für 4 sorgen：4を心配する／für 4 sorgen：4を調達する／für 4 sorgen：4を引き起こす／sich um 4 sorgen：4を心配する"},
  {"id":"ger-v150","subject":"german","c":1,"s":"基本動詞200","n":150,"d":"A","type":"input","q":"基本動詞 No.150：話す／4 sprechen：4を話す に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["sprechen"],"caseSensitive":false,"aText":"sprechen","e":"sprechen：話す／4 sprechen：4を話す"},
  {"id":"ger-v151","subject":"german","c":1,"s":"基本動詞200","n":151,"d":"A","type":"input","q":"基本動詞 No.151：跳ぶ に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["springen"],"caseSensitive":false,"aText":"springen","e":"springen：跳ぶ"},
  {"id":"ger-v152","subject":"german","c":1,"s":"基本動詞200","n":152,"d":"A","type":"input","q":"基本動詞 No.152：立っている に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["stehen"],"caseSensitive":false,"aText":"stehen","e":"stehen：立っている"},
  {"id":"ger-v153","subject":"german","c":1,"s":"基本動詞200","n":153,"d":"A","type":"input","q":"基本動詞 No.153：登る／上がる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["steigen"],"caseSensitive":false,"aText":"steigen","e":"steigen：登る／上がる"},
  {"id":"ger-v154","subject":"german","c":1,"s":"基本動詞200","n":154,"d":"A","type":"input","q":"基本動詞 No.154：4を立てる、4を置く／sich stellen：立つ に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["stellen"],"caseSensitive":false,"aText":"stellen","e":"stellen：4を立てる、4を置く／sich stellen：立つ"},
  {"id":"ger-v155","subject":"german","c":1,"s":"基本動詞200","n":155,"d":"A","type":"input","q":"基本動詞 No.155：死ぬ／an 3 sterben：3で死ぬ に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["sterben"],"caseSensitive":false,"aText":"sterben","e":"sterben：死ぬ／an 3 sterben：3で死ぬ"},
  {"id":"ger-v156","subject":"german","c":1,"s":"基本動詞200","n":156,"d":"A","type":"input","q":"基本動詞 No.156：（大学で）学ぶ／4を学ぶ に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["studieren"],"caseSensitive":false,"aText":"studieren","e":"studieren：（大学で）学ぶ／4を学ぶ"},
  {"id":"ger-v157","subject":"german","c":1,"s":"基本動詞200","n":157,"d":"A","type":"input","q":"基本動詞 No.157：4をさがす／nach 3 suchen：3をさがす／zu 不定詞 suchen：不定詞しようと努める に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["suchen"],"caseSensitive":false,"aText":"suchen","e":"suchen：4をさがす／nach 3 suchen：3をさがす／zu 不定詞 suchen：不定詞しようと努める"},
  {"id":"ger-v158","subject":"german","c":1,"s":"基本動詞200","n":158,"d":"A","type":"input","q":"基本動詞 No.158：踊る／4を踊る に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["tanzen"],"caseSensitive":false,"aText":"tanzen","e":"tanzen：踊る／4を踊る"},
  {"id":"ger-v159","subject":"german","c":1,"s":"基本動詞200","n":159,"d":"A","type":"input","q":"基本動詞 No.159：4を分ける／4 mit 3 teilen：4を3と分け合う に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["teilen"],"caseSensitive":false,"aText":"teilen","e":"teilen：4を分ける／4 mit 3 teilen：4を3と分け合う"},
  {"id":"ger-v160","subject":"german","c":1,"s":"基本動詞200","n":160,"d":"A","type":"input","q":"基本動詞 No.160：参加する／an 3 teilnehmen：3に参加する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["teilnehmen"],"caseSensitive":false,"aText":"teilnehmen","e":"teilnehmen：参加する／an 3 teilnehmen：3に参加する"},
  {"id":"ger-v161","subject":"german","c":1,"s":"基本動詞200","n":161,"d":"A","type":"input","q":"基本動詞 No.161：4を殺す に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["töten"],"caseSensitive":false,"aText":"töten","e":"töten：4を殺す"},
  {"id":"ger-v162","subject":"german","c":1,"s":"基本動詞200","n":162,"d":"A","type":"input","q":"基本動詞 No.162：4を運ぶ／4を支える／4を身につけている に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["tragen"],"caseSensitive":false,"aText":"tragen","e":"tragen：4を運ぶ／4を支える／4を身につけている"},
  {"id":"ger-v163","subject":"german","c":1,"s":"基本動詞200","n":163,"d":"A","type":"input","q":"基本動詞 No.163：夢を見る／4を夢にみる／von 3 träumen：3を夢にみる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["träumen"],"caseSensitive":false,"aText":"träumen","e":"träumen：夢を見る／4を夢にみる／von 3 träumen：3を夢にみる"},
  {"id":"ger-v164","subject":"german","c":1,"s":"基本動詞200","n":164,"d":"A","type":"input","q":"基本動詞 No.164：4に当てる／4に当たる／4に出会う に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["treffen"],"caseSensitive":false,"aText":"treffen","e":"treffen：4に当てる／4に当たる／4に出会う"},
  {"id":"ger-v165","subject":"german","c":1,"s":"基本動詞200","n":165,"d":"A","type":"input","q":"基本動詞 No.165：4を駆り立てる／4を動かす／漂う に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["treiben"],"caseSensitive":false,"aText":"treiben","e":"treiben：4を駆り立てる／4を動かす／漂う"},
  {"id":"ger-v166","subject":"german","c":1,"s":"基本動詞200","n":166,"d":"A","type":"input","q":"基本動詞 No.166：4を分ける／4 von 3 trennen：4を3から分ける に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["trennen"],"caseSensitive":false,"aText":"trennen","e":"trennen：4を分ける／4 von 3 trennen：4を3から分ける"},
  {"id":"ger-v167","subject":"german","c":1,"s":"基本動詞200","n":167,"d":"A","type":"input","q":"基本動詞 No.167：歩む／踏む に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["treten"],"caseSensitive":false,"aText":"treten","e":"treten：歩む／踏む"},
  {"id":"ger-v168","subject":"german","c":1,"s":"基本動詞200","n":168,"d":"A","type":"input","q":"基本動詞 No.168：4を飲む に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["trinken"],"caseSensitive":false,"aText":"trinken","e":"trinken：4を飲む"},
  {"id":"ger-v169","subject":"german","c":1,"s":"基本動詞200","n":169,"d":"A","type":"input","q":"基本動詞 No.169：4をする／振舞う／作用する／es mit 3 zu tun haben：3に関わる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["tun"],"caseSensitive":false,"aText":"tun","e":"tun：4をする／振舞う／作用する／es mit 3 zu tun haben：3に関わる"},
  {"id":"ger-v170","subject":"german","c":1,"s":"基本動詞200","n":170,"d":"A","type":"input","q":"基本動詞 No.170：4を練習する／練習する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["üben"],"caseSensitive":false,"aText":"üben","e":"üben：4を練習する／練習する"},
  {"id":"ger-v171","subject":"german","c":1,"s":"基本動詞200","n":171,"d":"A","type":"input","q":"基本動詞 No.171：4を翻訳する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["übersetzen"],"caseSensitive":false,"aText":"übersetzen","e":"übersetzen：4を翻訳する"},
  {"id":"ger-v172","subject":"german","c":1,"s":"基本動詞200","n":172,"d":"A","type":"input","q":"基本動詞 No.172：4を忘れる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["vergessen"],"caseSensitive":false,"aText":"vergessen","e":"vergessen：4を忘れる"},
  {"id":"ger-v173","subject":"german","c":1,"s":"基本動詞200","n":173,"d":"A","type":"input","q":"基本動詞 No.173：4を売る に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["verkaufen"],"caseSensitive":false,"aText":"verkaufen","e":"verkaufen：4を売る"},
  {"id":"ger-v174","subject":"german","c":1,"s":"基本動詞200","n":174,"d":"A","type":"input","q":"基本動詞 No.174：4を失う に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["verlieren"],"caseSensitive":false,"aText":"verlieren","e":"verlieren：4を失う"},
  {"id":"ger-v175","subject":"german","c":1,"s":"基本動詞200","n":175,"d":"A","type":"input","q":"基本動詞 No.175：3に4を約束する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["versprechen"],"caseSensitive":false,"aText":"versprechen","e":"versprechen：3に4を約束する"},
  {"id":"ger-v176","subject":"german","c":1,"s":"基本動詞200","n":176,"d":"A","type":"input","q":"基本動詞 No.176：4を理解する／zu 不定詞 verstehen：不定詞する術を心得ている に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["verstehen"],"caseSensitive":false,"aText":"verstehen","e":"verstehen：4を理解する／zu 不定詞 verstehen：不定詞する術を心得ている"},
  {"id":"ger-v177","subject":"german","c":1,"s":"基本動詞200","n":177,"d":"A","type":"input","q":"基本動詞 No.177：4を紹介する／4を表す／sich 4 vorstellen：4を想像する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["vorstellen"],"caseSensitive":false,"aText":"vorstellen","e":"vorstellen：4を紹介する／4を表す／sich 4 vorstellen：4を想像する"},
  {"id":"ger-v178","subject":"german","c":1,"s":"基本動詞200","n":178,"d":"A","type":"input","q":"基本動詞 No.178：起きている／über 4 wachen：4を見張っている に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["wachen"],"caseSensitive":false,"aText":"wachen","e":"wachen：起きている／über 4 wachen：4を見張っている"},
  {"id":"ger-v179","subject":"german","c":1,"s":"基本動詞200","n":179,"d":"A","type":"input","q":"基本動詞 No.179：成長する／増す／an 3 wachsen：3を増す に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["wachsen"],"caseSensitive":false,"aText":"wachsen","e":"wachsen：成長する／増す／an 3 wachsen：3を増す"},
  {"id":"ger-v180","subject":"german","c":1,"s":"基本動詞200","n":180,"d":"A","type":"input","q":"基本動詞 No.180：歩き回る／移動する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["wandern"],"caseSensitive":false,"aText":"wandern","e":"wandern：歩き回る／移動する"},
  {"id":"ger-v181","subject":"german","c":1,"s":"基本動詞200","n":181,"d":"A","type":"input","q":"基本動詞 No.181：待つ／auf 4 warten：4を待つ に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["warten"],"caseSensitive":false,"aText":"warten","e":"warten：待つ／auf 4 warten：4を待つ"},
  {"id":"ger-v182","subject":"german","c":1,"s":"基本動詞200","n":182,"d":"A","type":"input","q":"基本動詞 No.182：4を洗う／sich waschen：体を洗う／sich 4 waschen：4を洗う に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["waschen"],"caseSensitive":false,"aText":"waschen","e":"waschen：4を洗う／sich waschen：体を洗う／sich 4 waschen：4を洗う"},
  {"id":"ger-v183","subject":"german","c":1,"s":"基本動詞200","n":183,"d":"A","type":"input","q":"基本動詞 No.183：4を起こす／4を呼び起こす に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["wecken"],"caseSensitive":false,"aText":"wecken","e":"wecken：4を起こす／4を呼び起こす"},
  {"id":"ger-v184","subject":"german","c":1,"s":"基本動詞200","n":184,"d":"A","type":"input","q":"基本動詞 No.184：泣く に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["weinen"],"caseSensitive":false,"aText":"weinen","e":"weinen：泣く"},
  {"id":"ger-v185","subject":"german","c":1,"s":"基本動詞200","n":185,"d":"A","type":"input","q":"基本動詞 No.185：1・形 werden：1・形になる／werden：生じる／zu 3 werden：（変化して）3になる／3（zuteil）werden：3に与えられる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["werden"],"caseSensitive":false,"aText":"werden","e":"werden：1・形 werden：1・形になる／werden：生じる／zu 3 werden：（変化して）3になる／3（zuteil）werden：3に与えられる"},
  {"id":"ger-v186","subject":"german","c":1,"s":"基本動詞200","n":186,"d":"A","type":"input","q":"基本動詞 No.186：4を投げる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["werfen"],"caseSensitive":false,"aText":"werfen","e":"werfen：4を投げる"},
  {"id":"ger-v187","subject":"german","c":1,"s":"基本動詞200","n":187,"d":"A","type":"input","q":"基本動詞 No.187：4と再会する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["wiedersehen"],"caseSensitive":false,"aText":"wiedersehen","e":"wiedersehen：4と再会する"},
  {"id":"ger-v188","subject":"german","c":1,"s":"基本動詞200","n":188,"d":"A","type":"input","q":"基本動詞 No.188：4を知っている／zu 不定詞 wissen：不定詞する術を心得ている に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["wissen"],"caseSensitive":false,"aText":"wissen","e":"wissen：4を知っている／zu 不定詞 wissen：不定詞する術を心得ている"},
  {"id":"ger-v189","subject":"german","c":1,"s":"基本動詞200","n":189,"d":"A","type":"input","q":"基本動詞 No.189：住む／泊まる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["wohnen"],"caseSensitive":false,"aText":"wohnen","e":"wohnen：住む／泊まる"},
  {"id":"ger-v190","subject":"german","c":1,"s":"基本動詞200","n":190,"d":"A","type":"input","q":"基本動詞 No.190：4を驚かせる／sich über 4 wundern：4に驚く に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["wundern"],"caseSensitive":false,"aText":"wundern","e":"wundern：4を驚かせる／sich über 4 wundern：4に驚く"},
  {"id":"ger-v191","subject":"german","c":1,"s":"基本動詞200","n":191,"d":"A","type":"input","q":"基本動詞 No.191：4を望む に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["wünschen"],"caseSensitive":false,"aText":"wünschen","e":"wünschen：4を望む"},
  {"id":"ger-v192","subject":"german","c":1,"s":"基本動詞200","n":192,"d":"A","type":"input","q":"基本動詞 No.192：4を支払う に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["zahlen"],"caseSensitive":false,"aText":"zahlen","e":"zahlen：4を支払う"},
  {"id":"ger-v193","subject":"german","c":1,"s":"基本動詞200","n":193,"d":"A","type":"input","q":"基本動詞 No.193：4を数える／zu 3 zählen：3に数えられる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["zählen"],"caseSensitive":false,"aText":"zählen","e":"zählen：4を数える／zu 3 zählen：3に数えられる"},
  {"id":"ger-v194","subject":"german","c":1,"s":"基本動詞200","n":194,"d":"A","type":"input","q":"基本動詞 No.194：4を（線で）描く に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["zeichnen"],"caseSensitive":false,"aText":"zeichnen","e":"zeichnen：4を（線で）描く"},
  {"id":"ger-v195","subject":"german","c":1,"s":"基本動詞200","n":195,"d":"A","type":"input","q":"基本動詞 No.195：4を見せる／4を示す に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["zeigen"],"caseSensitive":false,"aText":"zeigen","e":"zeigen：4を見せる／4を示す"},
  {"id":"ger-v196","subject":"german","c":1,"s":"基本動詞200","n":196,"d":"A","type":"input","q":"基本動詞 No.196：4を破壊する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["zerstören"],"caseSensitive":false,"aText":"zerstören","e":"zerstören：4を破壊する"},
  {"id":"ger-v197","subject":"german","c":1,"s":"基本動詞200","n":197,"d":"A","type":"input","q":"基本動詞 No.197：4を引く／移動する に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["ziehen"],"caseSensitive":false,"aText":"ziehen","e":"ziehen：4を引く／移動する"},
  {"id":"ger-v198","subject":"german","c":1,"s":"基本動詞200","n":198,"d":"A","type":"input","q":"基本動詞 No.198：4を閉める、4を閉じる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["zumachen"],"caseSensitive":false,"aText":"zumachen","e":"zumachen：4を閉める、4を閉じる"},
  {"id":"ger-v199","subject":"german","c":1,"s":"基本動詞200","n":199,"d":"A","type":"input","q":"基本動詞 No.199：疑う／an 3 zweifeln：3を疑う に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["zweifeln"],"caseSensitive":false,"aText":"zweifeln","e":"zweifeln：疑う／an 3 zweifeln：3を疑う"},
  {"id":"ger-v200","subject":"german","c":1,"s":"基本動詞200","n":200,"d":"A","type":"input","q":"基本動詞 No.200：4を強いる／4 zu 3 zwingen：4に3を強いる に当たるドイツ語の基本動詞を、不定形で答えなさい。","answers":["zwingen"],"caseSensitive":false,"aText":"zwingen","e":"zwingen：4を強いる／4 zu 3 zwingen：4に3を強いる"},

  {id:"phy-13",subject:"physics",c:1,s:"運動方程式",n:13,d:"A",type:"input",
   q:"質量2.0 kgの物体に6.0 Nの合力が働く。加速度の数値だけを答えなさい。",number:3,tolerance:0.001,unit:"m/s²",aText:"3",
   e:"a=F/m=6.0/2.0=3.0 m/s²。"},

  {id:"cla-13",subject:"classics",c:5,s:"返り点",n:13,d:"A",type:"choice",
   q:"漢文の訓読で、レ点が示す基本的な読み方として適切なものを選びなさい。",o:["直後の一字を先に読んで戻る","文末から逆順にすべて読む","その字を読まない","必ず二字飛ばして読む"],a:[1],
   e:"レ点は、下の一字を先に読んでから上の字へ戻ることを示す。"},
  {id:"cla-14",subject:"classics",c:5,s:"再読文字",n:14,d:"B",type:"choice",
   q:"『未』を再読文字として読むときの基本形として正しいものを選びなさい。",o:["いまだ〜ず","まさに〜べし","すべからく〜べし","あへて〜ず"],a:[1],
   e:"未は『いまだ〜ず』と再読する。"},
  {id:"cla-15",subject:"classics",c:5,s:"否定",n:15,d:"A",type:"input",
   q:"漢文の否定形『不〜』を、ひらがなで基本的にどう読むか答えなさい。",answers:["〜ず","ず","～ず"],aText:"〜ず",
   e:"不は基本的に『〜ず』と訓読して否定を表す。"}
];
