registerQuestionPack({
  subject:"physics", name:"物理", chapters:{1:"力学"},
  questions:[{
    id:"phy-rta-recognition-001",subject:"physics",c:1,s:"問題認識",n:1004,d:"A",type:"choice",rta:"recognition",
    q:"問題文に「糸がゆるむ」とあるとき、糸の張力Tとして直ちに置くべき値を選びなさい。",
    o:["T=0","T=mg","T=ma","T=μN"],a:[1],
    e:"糸は引くことしかできないため、ゆるんだ瞬間以後は張力T=0。"
  },{
    id:"phy-rta-rec-mech-002",subject:"physics",c:1,s:"条件判断",n:1105,d:"A",type:"choice",rta:"recognition",
    q:"物体が面から離れる瞬間。面から受ける垂直抗力Nは？",
    o:["N=0","N=mg","N=ma","N=μmg"],a:[1],
    e:"面は接触している間だけ物体を押す。離れる境界で垂直抗力は0。"
  },{
    id:"phy-rta-rec-mech-003",subject:"physics",c:1,s:"条件判断",n:1106,d:"B",type:"choice",rta:"recognition",
    q:"物体が静止したまま滑り出す直前。静止摩擦力の大きさfは？（垂直抗力N、静止摩擦係数μₛ）",
    o:["f=μₛN","f=0","f=μₖN","f=N/μₛ"],a:[1],
    e:"滑り出す直前は最大静止摩擦力に達する。それ以前は常にμₛNとは限らない。"
  },{
    id:"phy-rta-rec-mech-004",subject:"physics",c:1,s:"条件判断",n:1107,d:"B",type:"choice",rta:"recognition",
    q:"空気抵抗を無視して鉛直上向きに投げた物体が最高点にある瞬間。速度vと加速度aは？（上向きを正）",
    o:["v=0、a=−g","v=0、a=0","v>0、a=−g","v=0、a=+g"],a:[1],
    e:"最高点で一瞬速度は0になるが、重力は働き続けるため加速度は下向きの−g。"
  }]
});
